local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-f>f', builtin.find_files, {})
vim.keymap.set('n', '<C-f>g', builtin.git_files, {})
vim.keymap.set('n', '<C-f>s', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
