local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-f><C-f>', builtin.find_files, {})
vim.keymap.set('n', '<C-f><C-g>', builtin.git_files, {})
vim.keymap.set('n', '<C-f><C-s>', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
