local builtin = require("telescope.builtin")
vim.keymap.set("n", "<C-f><C-f>", builtin.find_files, {})
vim.keymap.set("n", "<C-f><C-g>", builtin.git_files, {})
vim.keymap.set("n", "<C-f><C-s>", builtin.live_grep, {})
vim.keymap.set("n", "<C-f><C-b>", builtin.buffers, {})
